apiVersion: rbac.authorization.k8s.io
kind: Role
metadata:
  name: pod-manager-binding
  namespace: dev-app  
subjects:
- kind: ServiceAccount
  name: sa-dev
  namespace: dev-app
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
